models/Items.php
<?php

namespace app\models;

use Yii;
use app\models\traits\MultiLanguageTrait;
use yii2tech\ar\linkmany\LinkManyBehavior;

/**
 * This is the model class for table "items".
 *
 * @property string $fiitem_id
 * @property string $fsitem_name
 * @property string $fsitem_old_desc
 * @property string $fsitem_picture
 * @property string $fsitem_small_desc
 * @property string $fspassport
 * @property string $fsparams_array
 * @property integer $fianother_customer
 * @property string $fsitem_customer
 * @property integer $fitemplate_id
 * @property integer $fiitem_catalog_id
 * @property string $fsarticle
 * @property string $fsprice_rur
 * @property string $fsprice_usd
 * @property string $fsprice_byn
 * @property integer $fiorder
 * @property string $fdcreate_date
 * @property string $finew
 * @property string $fsseo
 * @property boolean $new_flag
 *
 * @property ItemsPictures[] $itemsPictures
 * @property ParamsValues[] $paramsValues
 * @property Items[] $similarItems
 */
class Items extends \yii\db\ActiveRecord
{
    use MultiLanguageTrait;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'items';
    }

    public function behaviors()
    {
        return [
            'linkSimilarItemsBehavior' => [
                'class' => LinkManyBehavior::className(),
                'relation' => 'similarItems', // relation, which will be handled
                'relationReferenceAttribute' => 'similarItemIds', // virtual attribute, which is used for related records specification
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fsitem_name'], 'required'],
            [['fsitem_old_desc', 'fsitem_small_desc', 'fsparams_array', 'fsitem_before_text', 'fsseo', 'fsitem_bottom_text', 'fsitem_passport_text'], 'string'],
            [['fianother_customer', 'fitemplate_id', 'fiitem_catalog_id', 'fiorder', 'finew'], 'integer'],
            [['fsitem_name', 'fspassport', 'fsitem_picture', 'fsitem_customer'], 'string', 'max' => 255],
            [['fsarticle', 'fsprice_rur', 'fsprice_usd', 'fsprice_byn', 'fdcreate_date'], 'string', 'max' => 30],
            [['fsitem_name'], 'unique'],
            [['new_flag'], 'boolean'],
            [['fsitem_bottom_text_en', 'fsitem_small_desc_en','fsseo_en'], 'string'],
            ['similarItemIds', 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'fiitem_id' => Yii::t('app', 'Внутренний номер товара'),
            'fsitem_name' => Yii::t('app', 'Название товара'),
            'fsitem_old_desc' => Yii::t('app', 'Описание в старом формате'),
            'fsitem_picture' => Yii::t('app', 'Картинка товара'),
            'fsitem_small_desc' => Yii::t('app', 'Краткое описание'),
            'fsparams_array' => Yii::t('app', 'Fsparams Array'),
            'fianother_customer' => Yii::t('app', 'Признак конкурента'),
            'fsitem_customer' => Yii::t('app', 'Производитель'),
            'fitemplate_id' => Yii::t('app', 'Внутренний номер шаблона'),
            'fiitem_catalog_id' => Yii::t('app', 'Fiitem Catalog ID'),
            'fspassport' => Yii::t('app', 'fspassport'),
            'fsarticle' => Yii::t('app', 'Fsarticle'),
            'fsprice_rur' => Yii::t('app', 'Fsprice Rur'),
            'fsprice_usd' => Yii::t('app', 'Fsprice Usd'),
            'fsprice_byn' => Yii::t('app', 'Fsprice Byn'),
            'fiorder' => Yii::t('app', 'Fiorder'),
            'fsitem_before_text' => Yii::t('app', 'fsitem_before_text'),
            'fdcreate_date' => Yii::t('app', 'fdcreate_date'),
            'finew' => Yii::t('app', 'finew'),
            'fsseo' => Yii::t('app', 'fsseo'),
            'fisale_id' => Yii::t('app', 'Sales'),
            'fsitem_bottom_text' => Yii::t('app', 'fsitem_bottom_text'),
            'fsitem_passport_text' => Yii::t('app', 'Паспорт изделия (Описание)'),
            'fsprice_byn' => 'Цена BYN',
            'new_flag' => Yii::t('app', 'finew'),
            'fsitem_bottom_text_en' => Yii::t('app', 'fsitem_bottom_text') . ' En',
            'fsitem_small_desc_en' => Yii::t('app', 'Краткое описание') . ' En',
            'fsseo_en' => Yii::t('app', 'fsseo') . ' En',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParamsValues()
    {
        return $this->hasMany(ParamsValues::className(), ['fiitem_id' => 'fiitem_id']);
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMainCatalog()
    {
        return $this->hasOne(CatalogRu::className(), ['ficatalog_id' => 'ficatalog_id'])->viaTable('catalog_items', ['fiitem_id' => 'fiitem_id']);
    }

    public function getSimilarItems()
    {
        return $this
            ->hasMany(Items::className(), ['fiitem_id' => 'similar_item_id'])
            ->viaTable('{{%items__similar}}', ['item_id' => 'fiitem_id'])
        ;
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Slider;
use app\models\CatalogSearchRu;
use app\models\NewsSearch;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\validators\EmailValidator;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\ItemsSearch;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $slider = Slider::find()->where('fislide_visible = 1')->all();
        return $this->render('index', ['slider' => $slider]);
    }

    public function actionDownloads() {
        if(Yii::$app->request->get('type') !== null) {
            $type = (int) Yii::$app->request->get('type');
            if ($type == 1)
                $this->redirect('/cert');
            return $this->render('downloads-media', [ 'type' => $type]);
        }
        else {
            return $this->render('downloads');
        }
    }

    public function actionCooperation()
    {
        $result = false;
        if(Yii::$app->request->isPost) {

            $body = '';
            $body .= 'Имя: ' . "\t" . Yii::$app->request->post('name') . "\n";
            $body .= 'Телефон: ' . "\t" . Yii::$app->request->post('phone') . "\n";
            $body .= 'Страна: ' . "\t" . Yii::$app->request->post('country') . "\n";
            $body .= 'Город: ' . "\t" . Yii::$app->request->post('town') . "\n";
            $body .= 'Email: ' . "\t" . Yii::$app->request->post('mail') . "\n";
            $body .= 'Комментарий: ' . "\t" . Yii::$app->request->post('comment') . "\n";

            try {
                $result = Yii::$app->mailer->compose()
                    ->setTo('region1@fif.by')
                    ->setFrom([Yii::$app->request->post('mail') => Yii::$app->request->post('name')])
                    ->setSubject('Заявка на ' . (Yii::$app->request->post('type') == 'diller' ? 'дилера' : 'инсталлятора'))
                    ->setTextBody($body)
                    ->send();
            }
            catch(Exception $ex) {
                $result = false;
            }

        }
        return $this->render('cooperation', ['result' => $result]);
    }

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
        // $this->actionIndex();
    }

    public function actionCertificats() {
        return $this->render('sertification');
    }

    public function actionMail() {
        $mail = Yii::$app->request->post('data');
        if(empty($mail)) {
            echo "Введен пустой адрес";
            Yii::$app->response->statusCode = 500;
            return false;
        }
        else {
            $mail = @$mail[0]['value'];
            if(empty($mail)) {
                echo "Введен пустой адрес";
                Yii::$app->response->statusCode = 500;
                return false;
            }
            $mail = trim($mail);
            $validator = new EmailValidator();
            if($validator->validate($mail)) {
                $res = Yii::$app->db->createCommand('SELECT 1 FROM mail WHERE fsmail = :mail', [':mail' => $mail])->queryAll();
                if(empty($res)) {
                    Yii::$app->db->createCommand('INSERT INTO mail(fsmail) VALUES(:mail)', [':mail' => $mail])->execute();
                    Yii::$app->mailer->compose()
                        ->setTo($mail)
                        ->setFrom([Yii::$app->params['adminEmail'] => 'Евроавтоматика ФиФ'])
                        ->setSubject('Подписка на новости Евроавтоматика ФиФ')
                        ->setHtmlBody(<<<BODY
<p>Уважаемый клиент! Вы подписались на новостную рассылку "Евроавтоматика ФиФ". Вас ждут новинки, интересные способы применения и обзоры продукции!</p>
<p>Письмо сгенерировано автоматически сайтом www.fif.by</p>
<p>При возникновении вопросов напишите нам: region1@fif.by</p>
<hr>
С уважением, команда СООО "Евроавтоматика ФиФ"
BODY
                        )
                        ->send();
                }
            }
            else {
                echo "Неверный формат адреса email";
                Yii::$app->response->statusCode = 500;
                return false;
            }
        }
        echo 'Спасибо, ваша подписка успешно оформлена';
    }

    public function actionGetcats() {
        $id = (int)Yii::$app->request->post('cat');
        echo $this->renderAjax('getitems', ['id' => $id]);
        //echo $id;
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionContact()
    {
        return $this->render('contact');
    }

    public function actionSearch($query, $ajax = false)
    {
        $searchModel = new ItemsSearch();
        @$s['ItemsSearch']['q']=$query;
        $dataProvider = $searchModel->search($s);

        $searchModel2 = new NewsSearch();
        @$s['NewsSearch']['q']=$query;
        $dataProvider2 = $searchModel2->search($s);

        $searchModel3 = new CatalogSearchRu();
        @$s['CatalogSearchRu']['q']=$query;
        $dataProvider3 = $searchModel3->search($s);
        if($ajax) {
            $response=[];
            $limit = 10;
            $i = 0;
            if (($search=$dataProvider->getModels())!==null)
                foreach ($search as $row) {
                    $i++;
                    if ($i > $limit) break;
                    $response[]=[
                        'link'=>\yii\helpers\Url::to(['catalog/items', 'id' => $row['fiitem_id']]),
                        'label'=>$row['fsitem_name'],
                        'value'=>$row['fsitem_name'],
                        'query'=>$query,
                    ];
                }
            return json_encode($response);
        } else {
            return $this->render('search',[
                'searchModel'=>$searchModel,
                'dataProvider'=>$dataProvider,
                'dataProvider2'=>$dataProvider2,
                'dataProvider3'=>$dataProvider3,
            ]);
        }
    }
}

views/site/chose.php
<?php

use app\models\Selects;
use app\models\SelectsItems;

$selectsGeneral = Selects::find()->where('fiparent_id = 0 or fiparent_id is null')->all();
$selectsOther = Selects::find()->where('fiparent_id <> 0 AND fiparent_id is not null')->all();

$js = <<<EOF
    $(function () {
       window.setTimeout(function () {
           $('.choose_form').unbind('change');
           
           $('.choose_form li label').click(function() {
               $('#loader').show(0);
               var self = $(this);
               var index = $('.choosetabs li.act').attr('data-num');
               $('.choose_form_tab').removeClass('show');
               $('.choosetabs li').removeClass('act');
               if(index == 0) {
                    //var active = $('input[name=general]:checked').attr('value');
                    var active = self.closest('li').find('input').attr('value');
                    $('.choose_form_tab[data-tab="1"] li').hide();
                    $('.choose_form_tab[data-tab="1"] li[data-parent=' + active + ']').show();
                    $('.choose_form_tab[data-tab="1"]').addClass("show");
                    $('.choosetabs li[data-num="1"]').addClass('act');
                    $('#loader').hide(0);
               }
               if(index == 1) {
                    //var active = $('input[name=podcat]:checked').attr('value');
                    var active = self.closest('li').find('input').attr('value');
                    $.post('%url%', {cat : active})
                        .always(function() {
                            $('.choose_form_tab[data-tab="2"]').addClass("show");
                            $('.choosetabs li[data-num="2"]').addClass('act');
                            $('#loader').hide(0);
                        })
                        .done(function(data) {
                           $('.choose_form_tab[data-tab="2"]').html(data);
                        });
               }
           });
           
           
       });
       
    });
EOF;

$js = str_replace('%url%', \yii\helpers\Url::to(['site/getcats']), $js);

$this->registerJs($js);

?>

<div class="choosewrap">
    <div class="inner_width ">
        <div class="general_loader" id="loader">
            <img src="/images/loader.svg" />
        </div>
        <form class="choose_form">
            <ul class="choose_form_tab show" data-tab='0'>
                <?php foreach ($selectsGeneral as $sg): ?>
                    <li>
                        <input id="c<?php echo $sg->fiselect_id ?>" type="radio" value="<?php echo $sg->fiselect_id ?>"
                               name="general" hidden/>
                        <label for="c<?php echo $sg->fiselect_id ?>"><?php echo $sg->fsselect_name; ?></label>
                    </li>
                <?php endforeach; ?>
            </ul>
            <ul class="choose_form_tab " data-tab='1'>
                <?php foreach ($selectsOther as $sg): ?>
                    <li data-parent="<?php echo $sg->fiparent_id ?>">
                        <input id="c<?php echo $sg->fiselect_id ?>" type="radio" value="<?php echo $sg->fiselect_id ?>"
                               name="podcat" hidden/>
                        <label for="c<?php echo $sg->fiselect_id ?>"><?php echo $sg->fsselect_name; ?></label>
                    </li>
                <?php endforeach; ?>
            </ul>
            <ul class="choose_form_tab last" data-tab='2'>

            </ul>
        </form>
    </div>
</div>

views/site/contact.php
<?php
//require_once 'about_old.php'; return;
use app\models\SiteTemplates;

/** @var SiteTemplates $template */
$template = SiteTemplates::findOne(['fscode' => '/site/contacts']);
$this->title = $template->fstitle;
$this->seoFields = $template->fstemplate_seo;
eval("?>" . $template->fstemplate_code . "<?php ");
return;

?>
<?php

$js = <<< JS
    $(function(){
        $(".contactslist li").on("click", function(){
            var tabs = $(".contactslist li"),
                cont = $(".contactstabwrap .contactstab");
            tabs.removeClass("act");
            cont.removeClass("act");
            $(this).addClass("act");
            cont.eq($(".contactslist li").index(this)).addClass("act");

            return false;
        });
    });
JS;

$this->registerJs($js);

?>

<div class="breadcrumbs">
    <div class="inner_width">
        <a href="#"><i class="ichome"></i>Главная</a>
        <span class="curr">Контакты</span>
    </div>
</div>
<div class="page_ttl">
    <div class="inner_width">
        <h1>Контакты</h1>
    </div>
</div>
<div class="inner_width ovfl">
    <ul class="contactslist">
        <li class="act"><a href="#">Отдел продаж</a></li>
        <li><a href="#" class="line2">Служба технической поддержки</a></li>
        <li><a href="#">Отдел развития</a></li>
        <li><a href="#">Главный инженер</a></li>
        <li><a href="#">Приёмная</a></li>
    </ul>
    <div class="contactstabwrap">
        <div class="contactstab act">
            <div class="contactstab_info">
                <div class="contactstab_ttl">Отдел продаж</div>
                231300, Республика Беларусь, г. Лида, ул. Минская 18А <br>
                <a href="tel:+375 154 55 47 40">+375 154 55 47 40</a>  <br>
                <a href="mailto:support@fif.by">support@fif.by</a>
            </div>
            <div class="contactstab_map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2351.469841740677!2d25.273298115325858!3d53.88785254171363!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46de8a99cfba4df7%3A0x6dc359fe507fceaf!2z0JXQstGA0L7QsNCy0YLQvtC80LDRgtC40LrQsCDQpNC40KQ!5e0!3m2!1sru!2sru!4v1469520230018" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>
        <div class="contactstab">
            <div class="contactstab_info">
                <div class="contactstab_ttl">Служба технической поддержки:</div>
                231300, Республика Беларусь, г. Лида, ул. Минская 18А <br>
                <a href="tel:+375 154 55 47 40">+375 154 55 47 40</a>  <br>
                <a href="tel:+375 154 60 03 80">+375 154 60 03 80</a><br>
                <a href="tel:+375 29 869 56 06">+375 29 869 56 06</a> (07:00 - 18:00)<br>
                <a href="tel:+375 29 319 43 73">+375 29 319 43 73</a><br>
                <a href="tel:+8 (800) 707-99-49">+8 (800) 707-99-49</a> - для Российской Федерации <br>(бесплатный)<br>
                <a href="mailto:support@fif.by">support@fif.by</a>
            </div>
            <div class="contactstab_map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2351.469841740677!2d25.273298115325858!3d53.88785254171363!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46de8a99cfba4df7%3A0x6dc359fe507fceaf!2z0JXQstGA0L7QsNCy0YLQvtC80LDRgtC40LrQsCDQpNC40KQ!5e0!3m2!1sru!2sru!4v1469520230018" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>
        <div class="contactstab">
            <div class="contactstab_info">
                <div class="contactstab_ttl">Отдел развития</div>
                231300, Республика Беларусь, г. Лида, ул. Минская 18А <br>
                <a href="tel:+375 154 55 47 40">+375 154 55 47 40</a>  <br>
                <a href="mailto:support@fif.by">support@fif.by</a>
            </div>
            <div class="contactstab_map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2351.469841740677!2d25.273298115325858!3d53.88785254171363!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46de8a99cfba4df7%3A0x6dc359fe507fceaf!2z0JXQstGA0L7QsNCy0YLQvtC80LDRgtC40LrQsCDQpNC40KQ!5e0!3m2!1sru!2sru!4v1469520230018" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>
        <div class="contactstab">
            <div class="contactstab_info">
                <div class="contactstab_ttl">Главный инженер</div>
                231300, Республика Беларусь, г. Лида, ул. Минская 18А <br>
                <a href="tel:+375 154 55 47 40">+375 154 55 47 40</a>  <br>
                <a href="mailto:support@fif.by">support@fif.by</a>
            </div>
            <div class="contactstab_map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2351.469841740677!2d25.273298115325858!3d53.88785254171363!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46de8a99cfba4df7%3A0x6dc359fe507fceaf!2z0JXQstGA0L7QsNCy0YLQvtC80LDRgtC40LrQsCDQpNC40KQ!5e0!3m2!1sru!2sru!4v1469520230018" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>
        <div class="contactstab">
            <div class="contactstab_info">
                <div class="contactstab_ttl">Приёмная</div>
                231300, Республика Беларусь, г. Лида, ул. Минская 18А <br>
                <a href="tel:+375 154 55 47 40">+375 154 55 47 40</a>  <br>
                <a href="mailto:support@fif.by">support@fif.by</a>
            </div>
            <div class="contactstab_map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2351.469841740677!2d25.273298115325858!3d53.88785254171363!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46de8a99cfba4df7%3A0x6dc359fe507fceaf!2z0JXQstGA0L7QsNCy0YLQvtC80LDRgtC40LrQsCDQpNC40KQ!5e0!3m2!1sru!2sru!4v1469520230018" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>
    </div>
</div>

views/site/downloads.php
<?php
//require_once 'downloads_old.php'; return;
use app\models\SiteTemplates;

/** @var SiteTemplates $template */
$template = SiteTemplates::findOne(['fscode' => 'site/downloads']);
$this->title = $template->fstitle;
$this->seoFields = $template->fstemplate_seo;
eval("?>" . $template->fstemplate_code . "<?php ");
?>

views/site/downloads_old.php
<?php
use yii\helpers\Html;
use app\models\Sertificats;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Tabs;
use yii\data\ActiveDataProvider;
use app\models\PublicationFiles;
use yii\widgets\ListView;
use app\models\Publications;

/* @var $this yii\web\View */
/* @var bool $result */

$this->title = Yii::t('app', 'down.title');

$js = <<< JS

$(function() {

});

JS;

$this->registerJs($js);

?>

<?php

use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PublicationsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Publications');
?>

<div class="breadcrumbs">
    <div class="inner_width">
        <a href="<?php echo \yii\helpers\Url::to(['site/index']); ?>"><i class="ichome"></i>Главная</a>
        <span class="curr">Медиа</span>
    </div>
</div>
<div class="page_ttl">
    <div class="inner_width">
        <h1>Медиа</h1>
    </div>
</div>
<div class="inner_width clrmar mediacenter">
    <?php foreach (\app\models\Publications::$types as $index => $type): ?>
        <div class="blocklink media">
            <a href="/downloads?type=<?php echo $index; ?>">
                <div class="media_item ">
                    <img src="images/icons/media/i<?php echo $index+2; ?>.png" alt=""/>
                    <span><?php echo $type ?></span>
                </div>
            </a>
        </div>
    <?php endforeach; ?>
</div>
<div class="inner_width ">
    <div class="description">
        <div class="separator"></div>
        Тут должен быть сео текст для продвижения, если оне влезет в верху. Возможно изготовление (под заказ) автоматов на напряжение 24 В AC/DC, а также с другим диапазоном регулировки порога включения по освещённости или временными Монтаж
        Реле установить в месте, открытом для доступа дневного света, при изменении которого будет включаться/отключаться освещение. При монтаже необходимо учесть, чтобы свет от включаемого освещения не попадал на фотодатчик. Регулировку порога включения необходимо производить медленно и аккуратно.
    </div>
</div>

views/site/error.php
<div class="breadcrumbs">
    <div class="inner_width">
        <a href="<?php echo \yii\helpers\Url::to(['/']) ?>"><i class="ichome"></i>Главная</a>
    </div>
</div>
<div class="page_ttl">
    <div class="inner_width">
        <h1>Страница не найдена</h1>
    </div>
</div>
<div class="inner_width center">
    <div class="mess404">404 <span>Уважаемый  пользователь,  к  сожалению страница  на  которую вы  ссылались  не найдена</span></div>
    <a class="catalog_item_more big" href="<?php echo \yii\helpers\Url::to(['/']) ?>">Скорее домой!</a>
</div>

views/site/index.php
<?php
//require_once 'index_old.php'; return;
use app\models\SiteTemplates;

/** @var SiteTemplates $template */
$template = SiteTemplates::findOne(['fscode' => 'site/index']);
$this->title = $template->fstitle;
$this->seoFields = $template->fstemplate_seo;
eval("?>" . $template->fstemplate_code . "<?php ");
?>

views/site/item-search.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ButtonDropdown;

/** var array $item */

?>
<div class="col-xs-12 item-new-one padding-none <?php if($item['fisale_id']) echo "sale"?>" data-id="<?php echo $item['fiitem_id'] ?>">

    <?php
        $itemValues = @$itemsValues[$item['fiitem_id']];
        if(empty($itemValues)) {
            $itemValues = [];
        }
        $itemValues = array_map(
          function($el) {
            return @array_values($el)[0];
        }, $itemValues);
    ?>

    <div class="hidden-info" style="display: none;"><?php echo json_encode($itemValues) ?></div>
    <div class="col-xs-12 padding-none">
        <div class="desc col-xs-12 padding-none" data-toggle="tooltip" data-placement="top" title="<?php echo $item['fsitem_small_desc'] ?>">
            <div class="description">
                <p class="title"><?php echo Html::a(@$item->mainCatalog->fsname.' '.$item['fsitem_name'], \yii\helpers\Url::to(['catalog/items', 'id' => $item['fiitem_id']])) ?></p>
                <?php echo $item['fsitem_small_desc'] ?>
                    <?php /*if(!empty($itemsValues[$item['fiitem_id']])) {
                        $index = 0;
                        foreach(@$itemsValues[$item['fiitem_id']] as $id => $params) {
                            echo '<div class="col-xs-9 param-name padding-none"><div class="dots"></div><div class="name">',array_keys($params)[0], '</div></div><div class="col-xs-3 param-value padding-none">', array_values($params)[0], '</div>';
                            $index++;
                            if($index>=5) {
                                break;
                            }
                        }
                    }*/
                ?>
            </div>
        </div>
    </div>
</div>

views/site/sertification.php
<?php
//require_once 'sertification_old.php'; return;
use app\models\SiteTemplates;

/** @var SiteTemplates $template */
$template = SiteTemplates::findOne(['fscode' => 'site/certificats']);
$this->title = $template->fstitle;
$this->seoFields = $template->fstemplate_seo;
eval("?>" . $template->fstemplate_code . "<?php ");
?>