models/Items.php
<?php

namespace app\models;

use Yii;
use app\models\traits\MultiLanguageTrait;
use yii2tech\ar\linkmany\LinkManyBehavior;

/**
 * This is the model class for table "items".
 *
 * @property string $fiitem_id
 * @property string $fsitem_name
 * @property string $fsitem_old_desc
 * @property string $fsitem_picture
 * @property string $fsitem_small_desc
 * @property string $fspassport
 * @property string $fsparams_array
 * @property integer $fianother_customer
 * @property string $fsitem_customer
 * @property integer $fitemplate_id
 * @property integer $fiitem_catalog_id
 * @property string $fsarticle
 * @property string $fsprice_rur
 * @property string $fsprice_usd
 * @property string $fsprice_byn
 * @property integer $fiorder
 * @property string $fdcreate_date
 * @property string $finew
 * @property string $fsseo
 * @property boolean $new_flag
 *
 * @property ItemsPictures[] $itemsPictures
 * @property ParamsValues[] $paramsValues
 * @property Items[] $similarItems
 */
class Items extends \yii\db\ActiveRecord
{
    use MultiLanguageTrait;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'items';
    }

    public function behaviors()
    {
        return [
            'linkSimilarItemsBehavior' => [
                'class' => LinkManyBehavior::className(),
                'relation' => 'similarItems', // relation, which will be handled
                'relationReferenceAttribute' => 'similarItemIds', // virtual attribute, which is used for related records specification
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fsitem_name'], 'required'],
            [['fsitem_old_desc', 'fsitem_small_desc', 'fsparams_array', 'fsitem_before_text', 'fsseo', 'fsitem_bottom_text', 'fsitem_passport_text'], 'string'],
            [['fianother_customer', 'fitemplate_id', 'fiitem_catalog_id', 'fiorder', 'finew'], 'integer'],
            [['fsitem_name', 'fspassport', 'fsitem_picture', 'fsitem_customer'], 'string', 'max' => 255],
            [['fsarticle', 'fsprice_rur', 'fsprice_usd', 'fsprice_byn', 'fdcreate_date'], 'string', 'max' => 30],
            [['fsitem_name'], 'unique'],
            [['new_flag'], 'boolean'],
            [['fsitem_bottom_text_en', 'fsitem_small_desc_en','fsseo_en'], 'string'],
            ['similarItemIds', 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'fiitem_id' => Yii::t('app', 'Внутренний номер товара'),
            'fsitem_name' => Yii::t('app', 'Название товара'),
            'fsitem_old_desc' => Yii::t('app', 'Описание в старом формате'),
            'fsitem_picture' => Yii::t('app', 'Картинка товара'),
            'fsitem_small_desc' => Yii::t('app', 'Краткое описание'),
            'fsparams_array' => Yii::t('app', 'Fsparams Array'),
            'fianother_customer' => Yii::t('app', 'Признак конкурента'),
            'fsitem_customer' => Yii::t('app', 'Производитель'),
            'fitemplate_id' => Yii::t('app', 'Внутренний номер шаблона'),
            'fiitem_catalog_id' => Yii::t('app', 'Fiitem Catalog ID'),
            'fspassport' => Yii::t('app', 'fspassport'),
            'fsarticle' => Yii::t('app', 'Fsarticle'),
            'fsprice_rur' => Yii::t('app', 'Fsprice Rur'),
            'fsprice_usd' => Yii::t('app', 'Fsprice Usd'),
            'fsprice_byn' => Yii::t('app', 'Fsprice Byn'),
            'fiorder' => Yii::t('app', 'Fiorder'),
            'fsitem_before_text' => Yii::t('app', 'fsitem_before_text'),
            'fdcreate_date' => Yii::t('app', 'fdcreate_date'),
            'finew' => Yii::t('app', 'finew'),
            'fsseo' => Yii::t('app', 'fsseo'),
            'fisale_id' => Yii::t('app', 'Sales'),
            'fsitem_bottom_text' => Yii::t('app', 'fsitem_bottom_text'),
            'fsitem_passport_text' => Yii::t('app', 'Паспорт изделия (Описание)'),
            'fsprice_byn' => 'Цена BYN',
            'new_flag' => Yii::t('app', 'finew'),
            'fsitem_bottom_text_en' => Yii::t('app', 'fsitem_bottom_text') . ' En',
            'fsitem_small_desc_en' => Yii::t('app', 'Краткое описание') . ' En',
            'fsseo_en' => Yii::t('app', 'fsseo') . ' En',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParamsValues()
    {
        return $this->hasMany(ParamsValues::className(), ['fiitem_id' => 'fiitem_id']);
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMainCatalog()
    {
        return $this->hasOne(CatalogRu::className(), ['ficatalog_id' => 'ficatalog_id'])->viaTable('catalog_items', ['fiitem_id' => 'fiitem_id']);
    }

    public function getSimilarItems()
    {
        return $this
            ->hasMany(Items::className(), ['fiitem_id' => 'similar_item_id'])
            ->viaTable('{{%items__similar}}', ['item_id' => 'fiitem_id'])
        ;
    }

}

controllers/ItemsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Items;
use app\models\ItemsSearch;
use yii\base\Exception;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\filters\AccessControl;

/**
 * ItemsController implements the CRUD actions for Items model.
 */
class ItemsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['admin', 'create', 'update', 'view', 'delete', 'update-order', 'getall'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['getall'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Items models.
     * @return mixed
     */
    public function actionAdmin()
    {
        $this->layout = 'admin';
        $searchModel = new ItemsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('admin', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Items model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Items model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout = 'admin';
        $model = new Items();

        if (Yii::$app->request->isPost) {
            $model->finew = (int)@$_POST['Items']['finew'];
            if ((int)@$_POST['Items']['fisale_id'] == 0) {
                $model->fisale_id = null;
            } else {
                $model->fisale_id = (int)@$_POST['Items']['fisale_id'];
            }
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->finew = $model->new_flag;
            $model->save(false, ['finew']);

            $file = UploadedFile::getInstanceByName('Items[fsitem_picture]');

            if ($file) {
                $b = $file->saveAs(dirname(__FILE__) . '/../web/data/img/item_' . $model->fiitem_id . '.by.' . $file->extension);
                $model->fsitem_picture = 'data/img/item_' . $model->fiitem_id . '.by.' . $file->extension;
                $model->save();
                $filename = dirname(__FILE__) . '/../web/data/img/item_' . $model->fiitem_id . '.by.' . $file->extension;
                list($width, $height) = getimagesize($filename);
                $newwidth = 280;
                $newheight = $height / ($width / $newwidth);
                if (($width > 1000 || $height > 1000) && in_array($file->extension, ['jpg', 'jpeg', 'png'])) {
                    $thumb = imagecreatetruecolor($newwidth, $newheight);
                    switch ($file->extension) {
                        case 'jpg':
                        case 'jpeg':
                            $source = imagecreatefromjpeg($filename);
                            break;
                        case 'png':
                            $source = imagecreatefrompng($filename);
                            break;
                    }

                    imagecopyresized($thumb, $source, 0, 0, 0, 0, $newwidth, $newheight, $width, $height);

                    imagejpeg($thumb, $filename . '.small.jpg', 100);
                }
            }

            $file = UploadedFile::getInstanceByName('Items[fspassport]');

            if ($file) {
                $file->saveAs(dirname(__FILE__) . '/../web/data/files/item_' . $model->fiitem_id . '.by.' . $file->extension);
                $model->fspassport = 'data/files/item_' . $model->fiitem_id . '.by.' . $file->extension;
                $model->save();
            }

            $this->saveProps($model);
            $this->saveCats($model);

            return $this->redirect(['admin']);
            // return $this->redirect(['admin', 'page' => Yii::$app->request->post('page')]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'itemList' => $this->getItemList(),
            ]);
        }
    }

    /**
     * @param Items $model
     * @throws Exception
     * @throws \Exception
     * @throws \yii\db\Exception
     */
    private function saveCats(Items $model)
    {
        $cats = Yii::$app->request->post('cats', []);
        $cats = array_map('intval', $cats);
        $transaction = Yii::$app->db->beginTransaction();
        try {
            Yii::$app->db->createCommand('delete from catalog_items where fiitem_id = :itemid', ['itemid' => $model->fiitem_id])->execute();
            foreach ($cats as $cat) {
                Yii::$app->db->createCommand('insert into catalog_items(ficatalog_id, fiitem_id) values(:catalogid, :itemid)', ['catalogid' => $cat, 'itemid' => $model->fiitem_id])->execute();
            }
        } catch (Exception $ex) {
            $transaction->rollBack();
            throw $ex;
        }
        $transaction->commit();
    }

    /**
     * @param Items $model
     * @throws Exception
     * @throws \Exception
     * @throws \yii\db\Exception
     */
    private function saveProps(Items $model)
    {
        $props = Yii::$app->request->post('item-props', '');
        $props = explode("\n", $props);
        $props = array_map('trim', $props);
        $transaction = Yii::$app->db->beginTransaction();
        $index = 0;
        try {
            Yii::$app->db->createCommand('delete from params_values where fiitem_id = :item', ['item' => $model->fiitem_id])->execute();
            foreach ($props as $prop) {
                if ('' == trim($prop)) {
                    continue;
                }
                $prop = explode("|", $prop);
                if (count($prop) != 2) {
                    continue;
                    /*$transaction->rollBack();
                    throw new Exception('Fail to save prop');*/
                } else {
                    $prop = array_map('trim', $prop);
                    $propId = Yii::$app->db->createCommand('select fiparam_id from params_cat pc where pc.fsparam_name = :name', ['name' => trim($prop[0])])->queryOne();
                    if (empty($propId)) {
                        Yii::$app->db->createCommand('insert into params_cat(fsparam_name, fiparam_show_filter) values(:pname, 0)', ['pname' => $prop[0]])->execute();
                        $propId = Yii::$app->db->getLastInsertID();
                    } else {
                        $propId = $propId['fiparam_id'];
                    }
                    Yii::$app->db->createCommand('insert into params_values(fiitem_id,fiparam_id,fsparam_value,fiorder) values(:item,:param,:value,:order)', [
                        'item' => $model->fiitem_id,
                        'param' => $propId,
                        'value' => $prop[1],
                        'order' => $index++,
                    ])->execute();
                }
            }
        } catch (Exception $ex) {
            $transaction->rollBack();
            throw $ex;
        }
        $transaction->commit();
    }

    /**
     * Updates an existing Items model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $this->layout = 'admin';
        $model = $this->findModel($id);
        $oldImg = $model->fsitem_picture;
        $oldPassport = $model->fspassport;
        if (Yii::$app->request->isPost) {
            $model->finew = (int)@$_POST['Items']['finew'];
            if ((int)@$_POST['Items']['fisale_id'] == 0) {
                $model->fisale_id = null;
            } else {
                $model->fisale_id = (int)@$_POST['Items']['fisale_id'];
            }
        }

        $file = UploadedFile::getInstanceByName('Items[fsitem_picture]');
        $passport = UploadedFile::getInstanceByName('Items[fspassport]');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->finew = $model->new_flag;
            $model->save(false, ['finew']);
            if (!$file) {
                $model->fsitem_picture = $oldImg;
                $model->save();
            } else {
                $filename = dirname(__FILE__) . '/../web/' . $oldImg;
                if (!empty($oldImg) && file_exists($filename)) {
                    unlink($filename);
                }

                $b = $file->saveAs(dirname(__FILE__) . '/../web/data/img/item_' . $model->fiitem_id . '.by.' . $file->extension);
                $model->fsitem_picture = 'data/img/item_' . $model->fiitem_id . '.by.' . $file->extension;
                $model->save();
                $filename = dirname(__FILE__) . '/../web/data/img/item_' . $model->fiitem_id . '.by.' . $file->extension;
                list($width, $height) = getimagesize($filename);
                $newwidth = 280;
                $newheight = $height / ($width / $newwidth);

views/items/_form.php
<?php

use app\models\Sales;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\CatalogRu;
use app\models\CatalogItems;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\Items */
/* @var $form yii\widgets\ActiveForm */

$params = Yii::$app->db->createCommand('select CONCAT(pc.fsparam_name,"|",pv.fsparam_value) as prop from params_values pv left JOIN params_cat pc on pc.fiparam_id = pv.fiparam_id where pv.fiitem_id = :id order by pv.fiorder',['id' => (int)$model->fiitem_id])->queryAll();
$props = '';
foreach($params as $param) {
    $props .= $param['prop'] . "\n";
}

$parent = [];
$parentsQeury = CatalogRu::find()/*->where('fiparent_catalog_id IS NOT NULL')*/->all();
/** @var CatalogRu $parents */
foreach($parentsQeury as $parents) {
    $parent[$parents->ficatalog_id] = $parents->fsname;
}

$cats = [];
$catsItem = CatalogItems::find()->where(['fiitem_id' => $model->fiitem_id])->all();
/** @var CatalogItems $ci */
foreach($catsItem as $ci) {
    $cats[] = $ci->ficatalog_id;
}

$new = [0 => 'Нет', 1 => 'Да'];

$listSales = [
  0 => 'Нет'] + ArrayHelper::map(Sales::find()->all(),'fisale_id', 'fssale_name');

$js = <<< JS
$(function() {
    $('.items-form .catalogs').on('click', 'div .g-link', function() {
        $(this).closest('div').remove();
    });

    $('.items-form').on('click','.add-catalog', function() {
        if($('.catalogs').find('div[data-id=' + $('#current-catalog').val() + ']').length) {
            return false;
        }
        $('<div/>')
        .attr('data-id', $('#current-catalog').val())
        .append(
            $('<span/>')
                .addClass('name')
                .text($('#current-catalog :selected').text())
        )
        .append(
            $('<span/>')
                .addClass('g-link padding-left')
                .text('Удалить категорию')
        )
        .append(
            $('<input/>')
                .attr({'type' : 'hidden', 'name' : 'cats[]', 'value' : $('#current-catalog').val()})
        )
        .insertBefore($('#current-catalog'));
        return false;
    });
});

/*$(function() {
        $('#items-fsitem_picture').picEdit();
    });*/

JS;

$this->registerJs($js);


$this->registerJsFile('@web/js/ckeditor/ckeditor.js');
$this->registerJs("
$(function() {
        CKEDITOR.replace('items-fsitem_bottom_text',
            {
                height  : '400px',
                on: {
                instanceReady:function( ev ){
                   jQuery(CKEDITOR.instances['items-fsitem_bottom_text'].container.$).mouseleave(function() {
                      CKEDITOR.instances['items-fsitem_bottom_text'].updateElement();
                   });
                   CKEDITOR.instances['items-fsitem_bottom_text'].on('blur', function() {
                      CKEDITOR.instances['items-fsitem_bottom_text'].updateElement();
                   });
                }
             }
            });
        $('#items-fsitem_bottom_text').on('change', function() {
          CKEDITOR.instances['items-fsitem_bottom_text'].setData($(this).val());
        });
});            ");

// $this->registerJsFile('@web/js/cropper/jquery.imgareaselect.min.js', ['depends' => 'yii\web\JqueryAsset']);
?>

<div class="items-form">

    <?php $form = ActiveForm::begin([
        'options' => ['enctype'=>'multipart/form-data']
    ]); ?>

    <input type="hidden" name="page" value="<?php echo Yii::$app->request->get('page'); ?>" />

    <?= $form->field($model, 'fsitem_name')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'fsarticle')->textInput(['maxlength' => 30]) ?>

    <?= $form->field($model, 'fsprice_rur')->textInput(['maxlength' => 30]) ?>

    <?= $form->field($model, 'fsprice_usd')->textInput(['maxlength' => 30]) ?>

    <?= $form->field($model, 'fsprice_byn')->textInput(['maxlength' => 30]) ?>

    <?= $form->field($model, 'new_flag')->checkbox() ?>

    <?= $form->field($model, 'fsitem_before_text')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'fsitem_picture')->fileInput() ?>

    <?php if(strlen($model->fsitem_picture)): ?>
        <div class="form-group">
            <?php echo Html::img(Yii::$app->request->baseUrl . '/' . $model->fsitem_picture, ['style' => 'max-width:200px;max-height:200px;']); ?>
        </div>
    <?php endif; ?>

    <?= $form->field($model, 'fspassport')->fileInput() ?>

    <?php if(strlen($model->fspassport)): ?>
        <div class="form-group">
            <?php echo Html::a(Yii::t('app', 'fspassport'),Yii::$app->request->baseUrl . '/' . $model->fspassport); ?>
        </div>
    <?php endif; ?>

    <?= $form->field($model, 'fsitem_passport_text')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'fsitem_small_desc')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'fsitem_small_desc_en')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'fsseo')->textarea() ?>

    <?= $form->field($model, 'fsseo_en')->textarea() ?>

    <div class="form-group">
        <label class="control-label" for="items-props">Свойства товара (Название|Значение)</label>
        <?= Html::textarea('item-props', $props, ['class' => 'form-control', 'rows' => 10]) ?>
    </div>

    <div class="form-group catalogs">
        <?php foreach($cats as $cat): ?>
          <?php if(isset($parent[$cat])): ?>
            <div data-id="<?php echo $cat ?>">
                <span class="name"><?php echo $parent[$cat] ?></span><span class="g-link padding-left">Удалить категорию</span><input value="<?php echo $cat ?>" name="cats[]" type="hidden">
            </div>
          <?php endif;?>
        <?php endforeach; ?>
        <?php echo Html::dropDownList('active-cats', null, $parent, ['id' => 'current-catalog', 'class' => 'form-control', 'style' => 'display:inline;width:400px;']) ?>
        <?php echo Html::button(Yii::t('app', 'add.to.cat'), ['class' => 'btn add-catalog']) ?>
    </div>

    
    <div class="form-group" style="display: none;">
      <?php echo $form->field($model, 'finew')->dropDownList($new) ?>
    </div>
    

    <div class="form-group">
        <?php echo $form->field($model, 'fisale_id')->dropDownList($listSales); ?>
    </div>

    <div class="form-group">
        <?php echo $form->field($model, 'fsitem_bottom_text')->textarea(); ?>
    </div>

    <div class="form-group">
        <?php echo $form->field($model, 'fsitem_bottom_text_en')->textarea(); ?>
    </div>

    <?php if(!$model->isNewRecord): ?>
    <?php
        $itemModel = $model;
        $query = \app\models\ItemsPictures::find()->where(['fiitem_id' => $model->fiitem_id]);
        $dataProvider = new \yii\data\ActiveDataProvider([
            'query' => $query,
        ]);
    ?>
    <div class="form-group">
        <?= \yii\grid\GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                'fsname',

                'fsimage' => [
                    'attribute' => 'fsimage',
                    'class' => \yii\grid\DataColumn::className(),
                    'format' => 'raw',
                    'value' => function ($model) {
                        return Html::img(Yii::$app->request->baseUrl . '/' . $model->fsimage, ['style' => 'max-width:200px']);
                    },
                ],

                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{delete}',
                    'urlCreator'=>function($action, $model, $key, $index) use ($itemModel) {
                        return ['upload/' . $action,'id'=>$model->fiitem_pic_id, 'item' => $itemModel->fiitem_id, 'page' => (int)Yii::$app->request->get('page')];
                    },
                    'buttons' => [
                        'delete' => function($url, $model) {
                            return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url,
                                ['delete', 'id' => $model->fiitem_pic_id],
                                [
                                    'title' => 'Удалить',
                                    'data-pjax' => '1',
                                    'data-method' => 'post',
                                ]
                            );
                        }
                    ]
                ],
            ],
        ]); ?>
        <?= Html::a('Добавить изображение', \yii\helpers\Url::to(['upload/index','type' => 'image', 'item' => $model->fiitem_id, 'page' => Yii::$app->request->get('page', Yii::$app->request->post('page'))])) ?>
    </div>
    <?php endif; ?>

    <?= $form->field($model, 'similarItemIds')->label('Похожие товары')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(
            $itemList,
            'fiitem_id',
            function ($model) {return $model->fsitem_name;}
        ),
        'options' => ['prompt' => '', 'multiple' => true],
        'pluginOptions' => [
            'allowClear' => true,
            'maximumSelectionLength' => 3
        ],
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/items/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ItemsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="items-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'fiitem_id') ?>

    <?= $form->field($model, 'fsitem_name') ?>

    <?= $form->field($model, 'fsitem_old_desc') ?>

    <?= $form->field($model, 'fsitem_picture') ?>

    <?= $form->field($model, 'fsitem_small_desc') ?>

    <?php // echo $form->field($model, 'fsparams_array') ?>

    <?php // echo $form->field($model, 'fianother_customer') ?>

    <?php // echo $form->field($model, 'fsitem_customer') ?>

    <?php // echo $form->field($model, 'fitemplate_id') ?>

    <?php // echo $form->field($model, 'fiitem_catalog_id') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/items/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Items */

$this->title = Yii::t('app', 'Create {modelClass}', [
    'modelClass' => Yii::t('app','Items'),
]);
$this->params['admin'] = [
    'page_title' => $this->title,
    'main_title' => 'Товар',
    'main_url' => 'items/admin'
];
?>


<div class="items-create">

    <?= $this->render('_form', [
        'model' => $model,
        'itemList' => $itemList,
    ]) ?>

</div>

views/items/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Items */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => Yii::t('app','Item'),
]) . ' ' . $model->fsitem_name;

$this->params['admin'] = [
    'page_title' => $this->title,
    'main_title' => 'Товары',
    'main_url' => 'items/admin'
];
?>
<div class="items-update">


    <?= $this->render('_form', [
        'model' => $model,
        'itemList' => $itemList,
    ]) ?>

</div>

views/items/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Items */

$this->title = $model->fiitem_id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Items'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="items-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->fiitem_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->fiitem_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'fiitem_id',
            'fsitem_name',
            'fsitem_old_desc:ntext',
            'fsitem_picture',
            'fsitem_small_desc:ntext',
            'fsparams_array:ntext',
            'fianother_customer',
            'fsitem_customer',
            'fitemplate_id',
            'fiitem_catalog_id',
        ],
    ]) ?>

</div>